[package]
name = "NovelRT-sys"
version = "0.1.0"
authors = ["Kirill Mironov <arkrait04@gmail.com>"]
edition = "2018"
links = "NovelRT"
build = "src/build.rs"

[dependencies]
libc = "0.2.48"

[build-dependencies]
cmake = "0.1"
